apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert  #name of this object
spec:
  dnsNames:
    - crm2137.ddns.net
  secretName: example-cert
  issuerRef:
    name: letsencrypt-new
    kind: ClusterIssuer
