apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
data:
  # property-like keys; each key maps to a simple value
  databasePort: "27017"
  databaseHost: "{{ .Release.Name }}-mongodb-headless"
  MONGODB_URI: "mongodb://root:pass@{{ .Release.Name }}-mongodb-headless:27017"
  LOG_LEVEL: "info"
  PERSISTENCE: "true"
  # file-like keys
  application.properties: |
    server.port = 3000
    spring.application.name = demo